<?php

namespace Disney\DisneylandBundle\Repository;

/**
 * AttractionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttractionsRepository extends \Doctrine\ORM\EntityRepository
{
}
