<?php

namespace Disney\DisneylandBundle\Repository;

/**
 * HotelsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HotelsRepository extends \Doctrine\ORM\EntityRepository
{
}
