disney_disneyland:
    resource: "@DisneyDisneylandBundle/Resources/config/routing.yml"
    prefix:   /

disneylanddisney:
    resource: "@DisneylanddisneyBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
