home:
    path:     /
    defaults: { _controller: DisneyDisneylandBundle:Home:index }

attractions:
    path:     /attractions
    defaults: { _controller: DisneyDisneylandBundle:Home:index }

hotels:
    path:     /hotels
    defaults: { _controller: DisneyDisneylandBundle:Home:index }

restaurants:
    path:     /
    defaults: { _controller: DisneyDisneylandBundle:Home:index }

spectacles:
    path:     /spectacles
    defaults: { _controller: DisneyDisneylandBundle:Home:index }

offres:
    path:     /offres
    defaults: { _controller: DisneyDisneylandBundle:Home:index }

transports:
    path:     /transports
    defaults: { _controller: DisneyDisneylandBundle:Home:index }

shows:
    path:     /shows
    defaults: { _controller: DisneyDisneylandBundle:Home:index }
