home:
    path:     /
    defaults: { _controller: DisneyDisneylandBundle:Home:index }

attraction:
    path:     /
    defaults: { _controller: DisneyDisneylandBundle:Home:index }

restaurant:
    path:     /
    defaults: { _controller: DisneyDisneylandBundle:Home:index }

shows:
    path:     /
    defaults: { _controller: DisneyDisneylandBundle:Home:index }
